//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_MVC_Ganesh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointTbl
    {
        public int AppID { get; set; }
        public int Patient { get; set; }
        public int Doctor { get; set; }
        public int Receptionist { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DoctorTbl DoctorTbl { get; set; }
        public virtual PatientTbl PatientTbl { get; set; }
        public virtual ReceptionistTbl ReceptionistTbl { get; set; }
    }
}
