//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_MVC_Ganesh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientTbl()
        {
            this.PrescriptionTbls = new HashSet<PrescriptionTbl>();
            this.AppointTbls = new HashSet<AppointTbl>();
            this.ReportTbls = new HashSet<ReportTbl>();
        }
    
        public int PatId { get; set; }
        public string PatName { get; set; }
        public string PatPhone { get; set; }
        public string PatGen { get; set; }
        public System.DateTime PatDOB { get; set; }
        public string PatAdd { get; set; }
        public string PatAllegies { get; set; }
        public int AddBy { get; set; }
    
        public virtual ReceptionistTbl ReceptionistTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrescriptionTbl> PrescriptionTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointTbl> AppointTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportTbl> ReportTbls { get; set; }
    }
}
