//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_MVC_Ganesh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTbl
    {
        public int ReportId { get; set; }
        public System.DateTime TestDate { get; set; }
        public string TestSummary { get; set; }
        public int Laboratorian { get; set; }
        public int Patient { get; set; }
        public int TestName { get; set; }
    
        public virtual LaboratorianTbl LaboratorianTbl { get; set; }
        public virtual LabTestTbl LabTestTbl { get; set; }
        public virtual PatientTbl PatientTbl { get; set; }
    }
}
