//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinical_MVC_Ganesh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLogin
    {
        public int ID { get; set; }
        public string MailID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
